import { ZodiacSign } from './types';

export const ZODIAC_SIGNS: ZodiacSign[] = [
  {
    id: 'aries',
    name: 'Aries',
    symbol: '♈',
    dateRange: 'March 21 - April 19',
    element: 'Fire',
    quality: 'Cardinal',
    rulingPlanet: 'Mars',
    traits: ['Active', 'Demanding', 'Determined', 'Effective', 'Ambitious'],
    description: 'Aries is the first sign of the zodiac and signifies leadership.',
    color: '#FF4136',
    stone: 'Diamond'
  },
  {
    id: 'taurus',
    name: 'Taurus',
    symbol: '♉',
    dateRange: 'April 20 - May 20',
    element: 'Earth',
    quality: 'Fixed',
    rulingPlanet: 'Venus',
    traits: ['Reliable', 'Patient', 'Practical', 'Devoted', 'Stable'],
    description: 'Taurus is the sign of the Bull and represent stability and patience.',
    color: '#2ECC40',
    stone: 'Emerald'
  },
  {
    id: 'gemini',
    name: 'Gemini',
    symbol: '♊',
    dateRange: 'May 21 - June 20',
    element: 'Air',
    quality: 'Mutable',
    rulingPlanet: 'Mercury',
    traits: ['Adaptable', 'Outgoing', 'Intelligent', 'Indecisive', 'Impulsive'],
    description: 'Gemini is represent by the Twins, reflecting its dual nature.',
    color: '#FFDC00',
    stone: 'Pearl'
  },
  {
    id: 'cancer',
    name: 'Cancer',
    symbol: '♋',
    dateRange: 'June 21 - July 22',
    element: 'Water',
    quality: 'Cardinal',
    rulingPlanet: 'Moon',
    traits: ['Loyal', 'Emotional', 'Sympathetic', 'Persuasive', 'Tenacious'],
    description: 'Cancer is the sign of the Crab and is deeply intuitive and sentimental.',
    color: '#0074D9',
    stone: 'Ruby'
  },
  {
    id: 'leo',
    name: 'Leo',
    symbol: '♌',
    dateRange: 'July 23 - August 22',
    element: 'Fire',
    quality: 'Fixed',
    rulingPlanet: 'Sun',
    traits: ['Generous', 'Warm-hearted', 'Cheerful', 'Humorous', 'Creative'],
    description: 'Leo is the Lion of the zodiac, natural leaders and full of life.',
    color: '#FF851B',
    stone: 'Peridot'
  },
  {
    id: 'virgo',
    name: 'Virgo',
    symbol: '♍',
    dateRange: 'August 23 - September 22',
    element: 'Earth',
    quality: 'Mutable',
    rulingPlanet: 'Mercury',
    traits: ['Kind', 'Hardworking', 'Practical', 'Loyal', 'Shy'],
    description: 'Virgo is the Virgin, representing a deep sense of humanity.',
    color: '#3D9970',
    stone: 'Sapphire'
  },
  {
    id: 'libra',
    name: 'Libra',
    symbol: '♎',
    dateRange: 'September 23 - October 22',
    element: 'Air',
    quality: 'Cardinal',
    rulingPlanet: 'Venus',
    traits: ['Social', 'Fair-minded', 'Diplomatic', 'Gracious', 'Cooperative'],
    description: 'Libra is represent by the Scales, seeking balance and harmony.',
    color: '#7FDBFF',
    stone: 'Opal'
  },
  {
    id: 'scorpio',
    name: 'Scorpio',
    symbol: '♏',
    dateRange: 'October 23 - November 21',
    element: 'Water',
    quality: 'Fixed',
    rulingPlanet: 'Pluto',
    traits: ['Passionate', 'Stubborn', 'Resourceful', 'Brave', 'True Friend'],
    description: 'Scorpio is the Scorpion, known for their intensity and passion.',
    color: '#85144b',
    stone: 'Topaz'
  },
  {
    id: 'sagittarius',
    name: 'Sagittarius',
    symbol: '♐',
    dateRange: 'November 22 - December 21',
    element: 'Fire',
    quality: 'Mutable',
    rulingPlanet: 'Jupiter',
    traits: ['Optimistic', 'Loves freedom', 'Hilarious', 'Enthusiastic', 'Adventurous'],
    description: 'Sagittarius is the Archer, always searching for the meaning of life.',
    color: '#B10DC9',
    stone: 'Turquoise'
  },
  {
    id: 'capricorn',
    name: 'Capricorn',
    symbol: '♑',
    dateRange: 'December 22 - January 19',
    element: 'Earth',
    quality: 'Cardinal',
    rulingPlanet: 'Saturn',
    traits: ['Responsible', 'Disciplined', 'Self-control', 'Good managers', 'Prudent'],
    description: 'Capricorn is the Sea-Goat, representing time and responsibility.',
    color: '#111111',
    stone: 'Garnet'
  },
  {
    id: 'aquarius',
    name: 'Aquarius',
    symbol: '♒',
    dateRange: 'January 20 - February 18',
    element: 'Air',
    quality: 'Fixed',
    rulingPlanet: 'Uranus',
    traits: ['Progressive', 'Original', 'Independent', 'Humanitarian', 'Intelligent'],
    description: 'Aquarius is the Water-Bearer, deep thinkers and social reformers.',
    color: '#39CCCC',
    stone: 'Amethyst'
  },
  {
    id: 'pisces',
    name: 'Pisces',
    symbol: '♓',
    dateRange: 'February 19 - March 20',
    element: 'Water',
    quality: 'Mutable',
    rulingPlanet: 'Neptune',
    traits: ['Compassionate', 'Artistic', 'Intuitive', 'Gentle', 'Wise'],
    description: 'Pisces is represented by two fish swimming in opposite directions.',
    color: '#F012BE',
    stone: 'Aquamarine'
  }
];
